Predicting whether the borrower is likely to default on loan or not given specific information using Logistic Regression

# Importing important libraries

In [253]:
# For Visualization
import matplotlib as plt
# For working with dataset
import pandas as pd
import numpy as np
import sklearn
%matplotlib inline

# Dataset
The dataset used in this model consists of information(Income, Age, Loan amount, Loan to income ratio) on 2000 people and whether they defaulted their loan or not.

Dataset source - "https://raw.githubusercontent.com/ybifoundation/Dataset/main/Credit%20Default.csv"

In [254]:
dataset = pd.read_csv('creditcarddef.csv')

In [255]:
dataset.head(10)

Income        Age         Loan  Loan to Income  Default
0  66155.92510  59.017015  8106.532131        0.122537        0
1  34415.15397  48.117153  6564.745018        0.190752        0
2  57317.17006  63.108049  8020.953296        0.139940        0
3  42709.53420  45.751972  6103.642260        0.142911        0
4  66952.68885  18.584336  8770.099235        0.130990        1
5  24904.06414  57.471607    15.498598        0.000622        0
6  48430.35961  26.809132  5722.581981        0.118161        0
7  24500.14198  32.897548  2971.003310        0.121265        1
8  40654.89254  55.496853  4755.825280        0.116980        0
9  25075.87277  39.776378  1409.230371        0.056199        0

Checking for Null Values

In [256]:
dataset.isnull().sum()

Income            0
Age               0
Loan              0
Loan to Income    0
Default           0
dtype: int64

Splitting Dependent and Independent Variables

In [257]:
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

In [258]:
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03, 1.22536751e-01],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03, 1.90751581e-01],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03, 1.39939800e-01],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03, 1.24635659e-01],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03, 3.70856680e-02],
       [6.94365795e+04, 5.61526170e+01, 7.37883360e+03, 1.06267239e-01]])

In [259]:
y

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

# Splitting dataset into Train and Test Sets for comparision

In [260]:
from sklearn.model_selection import train_test_split

In [261]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

# Using Logistic Regression to get predictions

In [262]:
from sklearn.linear_model import LogisticRegression

In [263]:
logmodel = LogisticRegression(random_state=0)
logmodel.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [264]:
prediction = logmodel.predict(X_test)

# Checking Authenticity of the model

In [265]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [266]:
classification_report(y_test,prediction)

'              precision    recall  f1-score   support\n\n           0       0.91      0.98      0.94       506\n           1       0.80      0.51      0.62        94\n\n    accuracy                           0.90       600\n   macro avg       0.86      0.74      0.78       600\nweighted avg       0.90      0.90      0.89       600\n'

In [267]:
confusion_matrix(y_test,prediction)

array([[494,  12],
       [ 46,  48]], dtype=int64)

In [268]:
accuracy_score(y_test,prediction)

0.9033333333333333